[build]
  # Configuration pour le frontend
  command = "npm run build"
  publish = "frontEnd/dist"
  base = "frontEnd"

[build.environment]
  NODE_ENV = "production"

# Configuration des fonctions serverless
[functions]
  directory = "netlify/functions"

# Redirections pour l'API vers les fonctions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirections pour le frontend (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 