[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node src/server.mongodb-test.js"
healthcheckPath = "/api/config"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 