[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node src/server.production-simple.js"
healthcheckPath = "/api/config"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 