services:
  - type: web
    name: ats-backend
    env: node
    plan: free
    buildCommand: cd backEnd && yarn install
    startCommand: cd backEnd && yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 